version: "3"
services:
  app:
    build: ./docker
    ports:
      - 3000:8080
    environment:
      - WORKDIR=/workspace
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
